CREATE TABLE mpa (
    id_mpa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_mpa VARCHAR(10)
);

CREATE TABLE films(
    id_film INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_film VARCHAR(100),
    description VARCHAR(1000),
    release_date DATE,
    duration INTEGER,
    id_mpa INTEGER REFERENCES mpa (id_mpa)
);

CREATE TABLE genre (
    id_genre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_genre VARCHAR(50)
);

CREATE TABLE genre_films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_film INTEGER REFERENCES films (id_film),
    id_genre INTEGER REFERENCES genre (id_genre)
);

CREATE TABLE users (
    id_user INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100),
    login VARCHAR(100),
    name VARCHAR(100),
    birthday DATE
);

CREATE TABLE likes_films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_films INTEGER REFERENCES films (id_film),
    id_user INTEGER REFERENCES users (id_user)
);

CREATE TABLE friends (
    id INTEGER GENERATED  BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_user INTEGER REFERENCES users (id_user),
    id_friends INTEGER,
    friendship_status BOOLEAN
);

INSERT INTO mpa (name_mpa)
VALUES ('G'),
       ('PG'),
       ('PG-13'),
       ('R'),
       ('NC-17');

INSERT INTO genre (name_genre)
VALUES ('Комедия'),
       ('Драма'),
       ('Мультфильм'),
       ('Триллер'),
       ('Документальный'),
       ('Боевик');

